package Pract1;
// Generated 8/03/2016 03:03:34 PM by Hibernate Tools 4.3.1


import java.io.Serializable;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Cuentas generated by hbm2java
 */
@Entity
@Table(name="cuentas"
    ,schema="public"
)
public class Cuentas  implements java.io.Serializable {


     private Serializable identificador;
     private Serializable contasenia;
     private Set usuarioses = new HashSet(0);

    public Cuentas() {
    }

	
    public Cuentas(Serializable identificador, Serializable contasenia) {
        this.identificador = identificador;
        this.contasenia = contasenia;
    }
    public Cuentas(Serializable identificador, Serializable contasenia, Set usuarioses) {
       this.identificador = identificador;
       this.contasenia = contasenia;
       this.usuarioses = usuarioses;
    }
   
     @Id 

    
    @Column(name="Identificador", unique=true, nullable=false)
    public Serializable getIdentificador() {
        return this.identificador;
    }
    
    public void setIdentificador(Serializable identificador) {
        this.identificador = identificador;
    }

    
    @Column(name="Contasenia", nullable=false)
    public Serializable getContasenia() {
        return this.contasenia;
    }
    
    public void setContasenia(Serializable contasenia) {
        this.contasenia = contasenia;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="cuentas")
    public Set getUsuarioses() {
        return this.usuarioses;
    }
    
    public void setUsuarioses(Set usuarioses) {
        this.usuarioses = usuarioses;
    }




}


