package Pract1;
// Generated 8/03/2016 03:03:34 PM by Hibernate Tools 4.3.1


import java.io.Serializable;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Usuarios generated by hbm2java
 */
@Entity
@Table(name="usuarios"
    ,schema="public"
)
public class Usuarios  implements java.io.Serializable {


     private Serializable email;
     private Cuentas cuentas;
     private Serializable nombre;
     private Serializable apellidoPat;
     private Serializable apellidoMat;
     private int edad;
     private Serializable país;

    public Usuarios() {
    }

    public Usuarios(Serializable email, Cuentas cuentas, Serializable nombre, Serializable apellidoPat, Serializable apellidoMat, int edad, Serializable país) {
       this.email = email;
       this.cuentas = cuentas;
       this.nombre = nombre;
       this.apellidoPat = apellidoPat;
       this.apellidoMat = apellidoMat;
       this.edad = edad;
       this.país = país;
    }
   
     @Id 

    
    @Column(name="email", unique=true, nullable=false)
    public Serializable getEmail() {
        return this.email;
    }
    
    public void setEmail(Serializable email) {
        this.email = email;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="Identificador_Cuentas", nullable=false)
    public Cuentas getCuentas() {
        return this.cuentas;
    }
    
    public void setCuentas(Cuentas cuentas) {
        this.cuentas = cuentas;
    }

    
    @Column(name="Nombre", nullable=false)
    public Serializable getNombre() {
        return this.nombre;
    }
    
    public void setNombre(Serializable nombre) {
        this.nombre = nombre;
    }

    
    @Column(name="Apellido_Pat", nullable=false)
    public Serializable getApellidoPat() {
        return this.apellidoPat;
    }
    
    public void setApellidoPat(Serializable apellidoPat) {
        this.apellidoPat = apellidoPat;
    }

    
    @Column(name="Apellido_Mat", nullable=false)
    public Serializable getApellidoMat() {
        return this.apellidoMat;
    }
    
    public void setApellidoMat(Serializable apellidoMat) {
        this.apellidoMat = apellidoMat;
    }

    
    @Column(name="Edad", nullable=false)
    public int getEdad() {
        return this.edad;
    }
    
    public void setEdad(int edad) {
        this.edad = edad;
    }

    
    @Column(name="País", nullable=false)
    public Serializable getPaís() {
        return this.país;
    }
    
    public void setPaís(Serializable país) {
        this.país = país;
    }




}


